<a href="https://colab.research.google.com/github/EzeGB/PythonExcercises/blob/branchLunes/partialNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mat1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
rango = np.linalg.matrix_rank(mat1)
rango

np.int64(2)

In [ ]:
np.linalg.matrix_rank(np.array([[1,2],
                                [-1,1]]))

np.int64(2)

In [ ]:
np.linalg.matrix_rank(np.array([[1,2],
                                [2,4]]))

np.int64(1)

NORMA

In [ ]:
vec1 = np.array([1,2,3])
np.linalg.norm(vec1)
vec2 = np.array([-2,4,6])
diff = vec1 - vec2
np.linalg.norm(diff)

np.float64(4.69041575982343)

Indexación por rangos

In [ ]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat1[0,0]

np.int64(1)

In [ ]:
mat1[0,2]

np.int64(3)

In [ ]:
mat3 = mat1[0:(1+1),0:(1+1)]
mat3

array([[1, 2],
       [4, 5]])

In [ ]:
mat4 = mat1[1:(2+1),0:(1+1)]
mat4

array([[4, 5],
       [7, 8]])

In [ ]:
mat5 = mat1[0,0:(2+1)] ## or mat1[0,:]
mat5

array([1, 2, 3])

In [ ]:
mat6 = mat1[2,0:(1+1)]
mat6

array([7, 8])