<a href="https://colab.research.google.com/github/EzeGB/PythonExcercises/blob/correlation-and-linear-regression/regression_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [4]:
df = pd.read_csv('weight_height_lr.csv')
df.head(10)

,height,weight
0,59.0,30.0
1,128.0,64.0
2,190.0,96.0
3,57.0,29.0
4,111.0,57.0
5,104.0,51.0
6,51.0,23.0
7,173.0,86.0
8,103.0,53.0
9,139.0,70.0


In [5]:
X , y = df.iloc[:, 0], df.iloc[:, 1]

In [13]:
X = np.array(X)
X = X.reshape(-1, 1)

no need to touch dependent variable

In [14]:
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [17]:
lr.predict([[140],
            [160]])

array([70.15076004, 80.18559829])

In [16]:
print('w:', lr.coef_,'b:',lr.intercept_)

w: [0.50174191] b: -0.09310770774116861


In [19]:
y_pred = lr.predict(X)
y_pred

array([29.50966513, 64.12985709, 95.23785567, 28.5061813 , 55.60024458,
       52.08805119, 25.49572983, 86.70824315, 51.58630928, 69.64901813,
       89.21695272, 76.17166299, 72.6594696 , 40.04624529, 72.6594696 ,
       39.54450338, 27.50269748, 48.07411589, 27.50269748, 46.06714824,
       36.03230999, 59.11243797, 67.64205048, 66.13682474, 72.6594696 ,
       51.08456737, 33.02185852, 79.68385638, 36.03230999, 37.03579382,
       79.18211447, 53.09153502, 78.17863064, 58.10895414, 94.73611375,
       47.57237398, 47.07063207, 92.7291461 , 85.70475933, 79.18211447,
       46.56889015, 72.6594696 , 58.10895414, 64.12985709, 66.63856665,
       81.18908212, 31.01489087, 83.69779168, 70.15076004, 49.57934163,
       83.19604977, 91.72566228, 31.51663278, 83.69779168, 61.11940562,
       63.62811518, 44.06018059, 51.08456737, 31.51663278, 43.55843868,
       73.16121152, 31.51663278, 53.59327693, 29.50966513, 40.04624529,
       63.62811518, 27.50269748, 38.54101955, 58.61069605, 58.10

In [20]:
r2_score(y, y_pred)

0.9967481444894879

#correlation RORORORRORORO


In [25]:
x = np.array(df.iloc[:, 0])
y = np.array(y)

In [27]:
np.corrcoef(x,y)

array([[1.        , 0.99837275],
       [0.99837275, 1.        ]])